import * as fs from 'fs-extra';
import * as path from 'path';
import { glob } from 'glob';
import matter from 'gray-matter';

export const CONTEXT_DIR = '.context';

export interface ContextMeta {
  title: string;
  tags: string[];
  priority: string;
  updated: string | null;
  scope: string | null;
  status?: string;
  date?: string;
  [key: string]: unknown;
}

export interface ContextFile {
  path: string;
  meta: ContextMeta;
  content: string;
}

export interface AllContext {
  project: ContextFile | undefined;
  architecture: ContextFile | undefined;
  conventions: ContextFile | undefined;
  decisions: ContextFile[];
  modules: ContextFile[];
  all: ContextFile[];
}

export interface ContextStats {
  total: number;
  decisions: number;
  modules: number;
  stale: string[];
  hasProject: boolean;
  hasArchitecture: boolean;
  hasConventions: boolean;
}

export async function findRoot(startDir: string = process.cwd()): Promise<string | null> {
  let dir = startDir;
  while (dir !== path.parse(dir).root) {
    if (await fs.pathExists(path.join(dir, CONTEXT_DIR))) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return null;
}

export async function loadContextFile(filePath: string): Promise<ContextFile> {
  const raw = await fs.readFile(filePath, 'utf-8');
  const { data: meta, content } = matter(raw);
  return {
    path: filePath,
    meta: {
      title: meta.title || path.basename(filePath, '.md'),
      tags: meta.tags || [],
      priority: meta.priority || 'normal',
      updated: meta.updated || null,
      scope: meta.scope || null,
      ...meta,
    },
    content: content.trim(),
  };
}

export async function loadAllContext(rootDir: string): Promise<AllContext> {
  const contextDir = path.join(rootDir, CONTEXT_DIR);

  if (!await fs.pathExists(contextDir)) {
    throw new Error(`No .context/ directory found. Run 'contextd init' first.`);
  }

  const files = await glob('**/*.md', { cwd: contextDir, absolute: true });
  const contexts = await Promise.all(files.map(loadContextFile));

  return {
    project: contexts.find(c => c.path.endsWith('project.md')),
    architecture: contexts.find(c => c.path.endsWith('architecture.md')),
    conventions: contexts.find(c => c.path.endsWith('conventions.md')),
    decisions: contexts.filter(c => c.path.includes('/decisions/')),
    modules: contexts.filter(c => c.path.includes('/modules/')),
    all: contexts,
  };
}

export async function getRelevantContext(rootDir: string, filePaths: string[] = []): Promise<ContextFile[]> {
  const ctx = await loadAllContext(rootDir);
  const relevant: ContextFile[] = [];

  if (ctx.project) relevant.push(ctx.project);
  if (ctx.architecture && filePaths.length > 0) relevant.push(ctx.architecture);
  if (ctx.conventions) relevant.push(ctx.conventions);

  for (const mod of ctx.modules) {
    const modScope = mod.meta.scope;
    if (!modScope) continue;
    if (filePaths.some(f => f.includes(modScope))) relevant.push(mod);
  }

  for (const decision of ctx.decisions) {
    if (decision.meta.tags.length === 0) {
      relevant.push(decision);
      continue;
    }
    const pathStr = filePaths.join(' ');
    if (decision.meta.tags.some((tag: string) => pathStr.includes(tag))) {
      relevant.push(decision);
    }
  }

  return relevant;
}

export async function getContextStats(rootDir: string): Promise<ContextStats> {
  const ctx = await loadAllContext(rootDir);
  const now = new Date();

  const stale = ctx.all.filter(c => {
    if (!c.meta.updated) return true;
    const updated = new Date(c.meta.updated);
    const monthsOld = (now.getTime() - updated.getTime()) / (1000 * 60 * 60 * 24 * 30);
    return monthsOld > 3;
  });

  return {
    total: ctx.all.length,
    decisions: ctx.decisions.length,
    modules: ctx.modules.length,
    stale: stale.map(c => c.path),
    hasProject: !!ctx.project,
    hasArchitecture: !!ctx.architecture,
    hasConventions: !!ctx.conventions,
  };
}

export function buildExportOutput(contexts: ContextFile[], format: string): string {
  const sections: string[] = [];
  const now = new Date().toISOString();

  const header = format === 'claude-md'
    ? `# Project Context\n\n> Generated by contextd on ${now}\n> Edit files in .context/ — do not edit this file directly.\n`
    : `# AI Context\n# Generated by contextd on ${now}\n# Edit files in .context/ — do not edit this file directly.\n`;

  sections.push(header);

  const ordered = [
    ...contexts.filter(c => c.path.endsWith('project.md')),
    ...contexts.filter(c => c.path.endsWith('architecture.md')),
    ...contexts.filter(c => c.path.endsWith('conventions.md')),
    ...contexts.filter(c => c.path.includes('/modules/')),
    ...contexts.filter(c => c.path.includes('/decisions/')),
  ];

  const seen = new Set<string>();
  const unique = ordered.filter(c => {
    if (seen.has(c.path)) return false;
    seen.add(c.path);
    return true;
  });

  for (const ctx of unique) {
    if (!ctx.content) continue;
    if (ctx.path.includes('/decisions/')) {
      sections.push(`\n---\n\n## Decision: ${ctx.meta.title}\n\n${ctx.content}`);
    } else if (ctx.path.includes('/modules/')) {
      sections.push(`\n---\n\n## Module Context: ${ctx.meta.scope || ctx.meta.title}\n\n${ctx.content}`);
    } else {
      sections.push(`\n---\n\n${ctx.content}`);
    }
  }

  return sections.join('\n');
}
